### ISSUE TITLE
Support for google-api-php-client v2.0.0

### ISSUE THREAD

**Issue by xcodewarrier** [tomwalder/php-gds#71] opened 2015-11-29 13:49 UTC
Will there be support for [google-api-client v2.0.0](https://github.com/google/google-api-php-client/releases/tag/v2.0.0-RC2) and is there an estimated timeline for when this would be available?

Thanks for all the effort and work on this.

**Comment by tomwalder** [comment] 2015-11-29 22:44
Yes, I will be adding support for this. I do not have an ETA, but hopefully in the next couple of weeks.

This ticket is probably a duplicate of https://github.com/tomwalder/php-gds/issues/71

So I'll close it down.

**Closed by tomwalder** 2015-11-29 22:44 UTC
